### ISSUE TITLE
Is there a detailed tutorial?

### ISSUE THREAD

**Issue by sunxun-1** [qeeqbox/honeypots#1]
I can't use it

**Comment by giga-a** [comment]
Hey, thanks for opening this issue.
I do not have a detailed tutorial at this moment (I may add one later on).
What're the issues you're facing?

**Comment by sunxun-1** [comment]
I use this code

************************
from honeypots import QTelnetServer
qsshserver = QTelnetServer(port=23)
qsshserver.run_server(process=True)

************************


after cmd:=> telnet 127.0.0.1

Connecting 127.0.0.1...Unable to open the connection to the host.At port 23: connection failed


thank you

**Comment by sunxun-1** [comment]
Thank you very much, I made it!

**Comment by giga-a** [comment]
Great! do not forget to check the other projects 🛵
