### ISSUE TITLE
MySQL database logging?

### ISSUE THREAD

**Issue by Mr-Rein** [qeeqbox/honeypots#10]
Is there any way to log the received logins to a MySQL database?

**Comment by giga-a** [comment]
Hey @Mr-Rein, not at this moment but it's possible
postgres is supported already (FYI) 

Here is an example of the Chameleon project that uses postgres [config.json](https://github.com/qeeqbox/chameleon/blob/master/config.json)

```json
    "logs": "db",
    "postgres":"//test: test@127.0.0.1:9999/honeypots",
```

**Comment by Mr-Rein** [comment]
Ah yes I see, thank you for the quick response!

**Comment by Mr-Rein** [comment]
Hello again, I've looked into postgres but I'm not that advanced with databases. How is your database structured? Because I believe my data is not being stored in the database, I can't seem to find the structure on the Chameleon repo.

Thanks for this project tho! Really cool and usefull!

**Comment by giga-a** [comment]
@Mr-Rein I will add more info regarding the structure soon!

**Comment by Mr-Rein** [comment]
@giga-a That would be amazing! Thank you.

**Comment by giga-a** [comment]
I had to add a [new update](https://github.com/qeeqbox/honeypots/commit/a8288b7853d759eaf199b921f980efbdc21e8e12) where the db mode is available (The db mode was available only for Chameleon project)

E.g. config.json

```json
{
    "logs": "db",
    "logs_location": "",
    "syslog_address":"",
    "syslog_facility":0,
    "postgres":"//username:password@172.19.0.2:9999/honeypots",
    "filter": "",
    "interface": "",
    "honeypots": {
        "ftp": {
            "port": 21,
            "username": "test",
            "password": "test"
        }
    }
}
```

The output structure should be the same in all honeypots
```json
[
  {
    "id": 1,
    "date": "2021-11-18 06:06:42.304338+00",
    "data": {
      "server": "'ftp_server'",
      "action": "'process'",
      "status": "'success'",
      "ip": "'0.0.0.0'",
      "port": "21",
      "username": "'test'",
      "password": "'test'"
    }
  }
]
````
