### ISSUE TITLE
Daemonization

### ISSUE THREAD

**Issue by tglanz** [qeeqbox/honeypots#11]
Hi, Thank you for this great repository!

I Am running some pots as a linux service under systemd. This causes an issue with the application mechanism, specifically I get an

    EOFError: EOF when reading a line

which is caused due to [this line](https://github.com/qeeqbox/honeypots/blob/4b9a4e83026fa8c0b47667a38334c3b1e30e3c71/honeypots/__main__.py#L246) which makes sense since there is not stdin.

I modified the ```input('')``` to a busy loop and it exit on SIGTERM properly.

Would you say it's a valid change?

**Comment by nikAizuddin** [comment]
Chameleon daemonize Honeypots by passing `--chameleon` argument according to this [Dockerfile](https://github.com/extra2000/qeeqbox-chameleon/blob/6792f2cd09148cc12d29e667f1dd26a49ab4069a/honeypots-Dockerfile#L10).

I think you can use `--chameleon` and `config.json` to daemonize.

**Comment by tglanz** [comment]
I just get a ```[x] Chameleon mode``` and the program exit, is that the expected behavior?

Also, noticed I need to add "filter" and "interface" to config, left those empty.

**Comment by giga-a** [comment]
Hey @tglanz

> I modified the input('') to a busy loop and it exit on SIGTERM properly.
> 
> Would you say it's a valid change?

Would you be able to submit pull request with your changes so I check that?

**Comment by tglanz** [comment]
See [this](https://github.com/qeeqbox/honeypots/pull/12) - Just changed ```input('')``` to ```while True: sleep(1)```.

The thing is that it changes the way you exit the process.

**Comment by giga-a** [comment]
merged
