### ISSUE TITLE
Include X-Forwarded-For header

### ISSUE THREAD

**Issue by btkev123** [qeeqbox/honeypots#16]
As discussed in discussion #953 we need the possibility to forward X-Forwarded-For from origin (attacker) at honeypot, not from our loadbalancer.
Please implement it to the sourcecode.

**Comment by giga-a** [comment]
@btkev123 thanks for opening this issue, I'm looking..

**Comment by giga-a** [comment]
@btkev123  Done, It will be pushed in the next update 

```sh
honeypots_1     | {"action": "connection", "data": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-US,en;q=0.5", "Connection": "close", "Host": "0.0.0.0", "Upgrade-Insecure-Requests": "1", "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0", "X-Forwarded-For": "172.25.0.1", "X-Real-Ip": "172.25.0.1", "method": "GET", "uri": "/"}, "dest_ip": "0.0.0.0", "dest_port": "80", "server": "http_server", "src_ip": "172.25.0.1", "src_port": "59440", "timestamp": "2022-02-08T20:41:45.633407"}
```
```sh
"src_ip": "172.25.0.1"
"X-Forwarded-For": "172.25.0.1"
```

**Comment by btkev123** [comment]
Hello together,

sorry I am not very familiar with Github. Where can I see when the next update is scheduld or if it's already published?
I wanna check when we can expect to download the latest version and to use it.

Thanks for a short feedback.

Regards
Kevin

**Comment by giga-a** [comment]
Hey @btkev123, no worries! 

It's already pushed in 0.51 2 weeks ago

Here is a short fix, make sure that the honeypots package is 0.51, then add HONEYPOTS_OPTIONS environment variable with fix_get_client_ip on the end that's running the package

#### Explanation 
The honeypots packages as of now checks if options is included in the configuration file (.json), or passed as parameter, or as an environment variable
```py
   self.options = kwargs.get('options', '') or (hasattr(self, 'options') and self.options) or getenv('HONEYPOTS_OPTIONS', '') or ''
```

Then, it uses `fix_get_client_i` to get the `X-Forwarded-For` or `X-Real-IP`
```py
                if 'fix_get_client_ip' in _q_s.options:
                    with suppress(Exception):
                        raw_headers = dict(request.requestHeaders.getAllRawHeaders())
                        if b'X-Forwarded-For':
                            client_ip = check_bytes(raw_headers[b'X-Forwarded-For'][0])
                        elif b'X-Real-IP':
                            client_ip = check_bytes(raw_headers[b'X-Real-IP'][0])
```
So, doing something like this will work
```py
python3 -m honeypots --setup http --options fix_get_client_ip
```
or like this but you have an environment variable called `HONEYPOTS_OPTIONS` with `fix_get_client_ip`
```py
python3 -m honeypots --setup http
```

How are you running that package? and let me know if the previous steps helped or not!

**Comment by btkev123** [comment]
Hi GIga,

I will check it soon and give you feedback. Because my colleague, who should work on this, is currently not available and I will be on holidays next week I think I need some days.

I will get back to you asap.

Regards

**Comment by giga-a** [comment]
@btkev123 Okay, I will keep this issue open until it's fully resolved.
