### ISSUE TITLE
How to not drop the db when restarting the project

### ISSUE THREAD

**Issue by yybuuin** [qeeqbox/honeypots#17]
Every time I restart the project, the logs are deleted. Error updating options: pq: database "chameleon" does not exist when db_option = []

<img width="703" alt="image" src="https://user-images.githubusercontent.com/38856017/153990815-2fa579af-50db-4aa5-b736-0aeb257e71d7.png">

**Comment by giga-a** [comment]
Hey @yybuuin, sorry for the delay! I'm looking

**Comment by giga-a** [comment]
@yybuuin I pushed a new version 0.50 try this

```
{
    "logs": "db_postgres",
    "logs_location": "",
    "syslog_address":"",
    "syslog_facility":0,
    "postgres":"//username:password@172.19.0.2:9999/honeypots",
    "sqlite_file":"",
    "db_options":[],
    "sniffer_filter": "",
    "sniffer_interface": "",
    "honeypots": {
````
