### ISSUE TITLE
How do I get console output

### ISSUE THREAD

**Issue by sunxun-1** [qeeqbox/honeypots#2]
`[2021-04-13 15:12:33] [ssh] [connection] -> {"ip": "127.0.0.1", "port": 52429}
[2021-04-13 15:12:39] [ssh] [login] -> {"ip": "127.0.0.1", "password": "admin", "port": 52429, "status": "failed", "username": "admin"}`

I want to save the output of honeypot to a log or file. How can I get the output of the console?

**Comment by giga-a** [comment]
Hey! What is your OS?

**Comment by sunxun-1** [comment]
Windows

**Comment by giga-a** [comment]
I have pushed a new update that allows users to set their own logs. 

Uninstall the old honeypot version and install the new one honeypots==0.10

```python
from honeypots import QSSHServer, clean_all
from time import sleep

qdnsserver = QSSHServer(logs='all',logs_location='test')
qdnsserver.run_server(process=True, auto=True)
sleep(2)
qdnsserver.test_server()
qdnsserver.kill_server()
clean_all()
```

**Comment by sunxun-1** [comment]
Great! Thank you for providing such a great tool!

**Comment by giga-a** [comment]
You are welcome!

**Comment by giga-a** [comment]
Just a little update, I changed the way you log to directory or outputting it to terminal. Now, you will have to use a config file. This update was needed for the [chameleon](https://github.com/qeeqbox/chameleon) project

```
python3 -m honeypots --setup ssh --logs all --config config.json

#config.json
{
    "logs":"file,terminal",
    "logs_location":"/temp/honeypots_logs/"
} 
```
