### ISSUE TITLE
honeypots and systemd service

### ISSUE THREAD

**Issue by Firzum** [qeeqbox/honeypots#21]
Hello,

First of all many thanks for this great work.
I'm trying to install honeypots as a service with systemd integration.

My /etc/systemd/system/honeypots.service

[Unit]
After=network.target

[Service]
ExecStart=/usr/bin/python3 -m honeypots --setup ssh,mysql,http,https,ftp,ntp,postgres,httpproxy,socks5,elastic --config /etc/honeypots/config.json

[Install]
WantedBy=default.target

The service start perfectly but end as soon as its started, I suppose this is due to the parent process dying, I'm not sure, I'm not a specialist. I just want to make things clean and standard.
Any advice to help me ti achieve this ?

Thanks in advance.

Regards,

**Comment by Firzum** [comment]
More effective version 

[Unit]
After=network.target

[Service]
ExecStart=/usr/bin/python3 -m honeypots --setup ssh,mysql,http,https,ftp,ntp,postgres,httpproxy,socks5,elastic --config /etc/honeypots/config.json
TTYVTDisallocate=yes


[Install]
WantedBy=default.target

**Comment by giga-a** [comment]
@Firzum Sorry for the delay! And good job figuring that out.. I think it would be a good idea for you to add that snippet to the README.md?
