### ISSUE TITLE
qeeqbox sends a RST to the Client on some URLs

### ISSUE THREAD

**Issue by jk20004** [qeeqbox/honeypots#23]
We have a load Balancer in front and we use the "new" X-Forwarded-For Option for the Traffic.
When we count the send requests on the Load Balancer and compare them with the result on the qeeqbox there are requests missing.

The Problem is that the qeeqbox sends a RST back.

After further investigation we found that the URL is the reason for the reset from the qeeqbox .

Example:

```
> GET /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession HTTP/1.1
> Host: X.X.X.X
> User-Agent: curl/7.58.0
> Accept: */*
>
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
* stopped the pause stream!
* Closing connection 0
* TLSv1.3 (OUT), TLS Unknown, Unknown (21):
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

What Steps on the qeeqbox will help to get more details of the Reset?

**Comment by giga-a** [comment]
@jk20004 try now?
