### ISSUE TITLE
Getting empty results after installing honeypots

### ISSUE THREAD

**Issue by fabsfernandes** [qeeqbox/honeypots#24]
After installing honeypots via pip3, I'm getting no results for the following commands:

`python3 -m honeypots --setup all`
`python3 -m honeypots --list`

Nothing happens -- no success, no error, no log
Any idea of what could be happening?

Python 3.6.9
Ubuntu 18.04

**Comment by jvgassel** [comment]
What does 'pip show honeypots' show?

**Comment by tobias-dietz** [comment]
Hi,

I had the same issue on CentOS 8 with Python 3.6. I've installed Python 3.8, now it works as expected.

Kind regards
