### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by gappymate** [qeeqbox/honeypots#25]
Hello.

First of all, thank you for providing this awesome repository.

Now to my question: this project is licensed under AGPL. That means, that if the programs are provided over the network, the user has to be able to download the source code. Since this is about honeypots, what are the implications? The idea behind honeypots is that they dont expose themselves as honeypots. Providing the source code would essentially do it. 

Or do I have a misunderstanding here? The question in other words would be: how can I use this project to run honeypots, compliant with the license?

Thanks.

**Comment by giga-a** [comment]
My interpretation of that licensee is you will have to provide the source code if you modify it
