### ISSUE TITLE
Grok patterns

### ISSUE THREAD

**Issue by fredericgoossens** [qeeqbox/honeypots#26]
Someone who has grok paterns for this so it can be parsed using logstash?

**Comment by FreddyTheNipple** [comment]
Made this one for the ftp service:

'timestamp': '%{TIMESTAMP_ISO8601:timestamp}', 'server': '%{WORD:service}', 'action': '%{WORD:action}', 'data': {'cmd': '%{WORD:cmd}', 'args': %{QUOTEDSTRING:args}}, 'src_ip': '%{IP:src_ip}', 'src_port': '%{NUMBER:src_port}', 'dest_ip': '%{IP:dest_ip}', 'dest_port': '%{NUMBER:dest_port}'

**Comment by Just5KY** [comment]
Just FYI,
Logstash has JSON filter plugin which will parse it out

```yml
input {
}

filter {
json {
source => "message"
}
}

output {
}
