### ISSUE TITLE
How can I add files and folders in SMB server

### ISSUE THREAD

**Issue by abdbacha** [qeeqbox/honeypots#3]
Hi,
I was wondering if I can put some files and folders as attractions in the SMB server.
Is this possible ?

**Comment by giga-a** [comment]
Hey @abdbacha! I have pushed a new update that allows attaching any folder as `name:target_folder` or multiple folders as `name:target_folder,name:target_folder` (The folders can contains files) to the SMB honeypot - This option is done by passing the folders in the config.json optional file

E.g. config.json contains 2 folders backup as r&dbackup, and secret as secret
```json
{
    "logs":"terminal",
    "logs_location":"",
    "honeypots": {
        "smb": {
            "port": 4545,
            "ip": "0.0.0.0",
            "username": "test",
            "password": "test",
            "folders":"r&dbackup:/backup,secret:/secret"
            }
        }
}
```

Now, run honeypots with the config file
```bash
$ honeypots --setup smb --config config.json
[x] Use [Enter] to exit or python3 -m honeypots --kill
[x] config.json file overrides --ip, --port, --username and --password
[x] Parsing honeypot [normal]
[2021-06-30 06:06:57] [smb] [process] -> {"folders": "r&dbackup:/backup,secret:/secret", "ip": "0.0.0.0", "password": "test", "port": 445, "status": "success", "username": "test"}
[x] Everything looks good!
```

Testing the honeypots and shares with smb client
```
IPC$
R&DBACKUP
SECRET
```

**Comment by abdbacha** [comment]
Hey @giga-a 
I tried it and it works fine, I was able to add multiple folders, subfolders and files
But when I try to get a file this error appears
`getattrib: NT_STATUS_INVALID_NETWORK_RESPONSE`
And the received folder will be empty.
can you help me ?!
