### ISSUE TITLE
SSH server doesn't offer password auth option, only SSH-RSA

### ISSUE THREAD

**Issue by AndreC10002** [qeeqbox/honeypots#34]
Setting up a SSH honeypot and found that it is enforcing SSH-RSA authentication, not letting a client provide username and password as credentials. Configuration file:

{
"logs": "file,terminal,json",
"logs_location": "/var/log/honeypots/",
"syslog_address": "",
"syslog_facility": 0,
"honeypots": {
"ssh":{
"port":22,
"ip":"0.0.0.0",
"username":"admin",
"password":"abc123",
"log_file_name":"ssh.log",
"max_bytes":1000000,
"backup_count":10,
"options":["capture_commands","fix_get_client_ip"]
}
}
}

Couldn't find an option to change this behavior. Would be more useful if the honeypot could accept only a username and password.

**Comment by donadelden** [comment]
Any update on this issue?
