### ISSUE TITLE
Single log file

### ISSUE THREAD

**Issue by desoul99** [qeeqbox/honeypots#4]
Hi o/.
I was wondering if it was possible to have a centralized log file, instead of creating new ones for each new event. This way one could monitor a single file instead of the entire folder.

Also, I've tried testing the DNS honeypot using nslookup and dig without luck, although the integrated startup test works just fine. Am i missing something? I've tried testing other ones like LDAP or SMB and they work just fine.

Thanks!

**Comment by giga-a** [comment]
Hey!

Thanks for submitting this issue,

> I was wondering if it was possible to have a centralized log file, instead of creating new ones for each new event. This way one could monitor a single file instead of the entire folder.

Did you mean; it creates log files for each new honeypots? (This project does not log for each new event, but for each new honeypot and handler because each has different UUID). That said, you can have a centralized log file by using syslog in a config file.

Here is an example of a syslog server that's running on ip:port 10.0.0.1:514
 
```bash
honeypots --setup ssh,ftp --config config.json
```

```json
config.json
{
    "logs": "syslog",
    "logs_location": "",
    "syslog_address":"udp://10.0.0.1:514",
    "syslog_facility":3,
    "honeypots": {
        "ftp": {
            "port": 21,
            "ip": "0.0.0.0",
            "username": "test",
            "password": "test"
            }
        },
        "ssh": {
            "port": 22,
            "ip": "0.0.0.0",
            "username": "test",
            "password": "test"
            }
        }
}
```

> Also, I've tried testing the DNS honeypot using nslookup and dig without luck, although the integrated startup test works just fine. Am i missing something? I've tried testing other ones like LDAP or SMB and they work just fine.

I do not think you're missing anything, It seems that the DNS honeypot needs some updates..

Glad that you tested LDAP and SMB!

**Comment by desoul99** [comment]
Yes my bad, i was testing the software and therefore it kept creating new files, so i thought it created new ones for each event.
I tried setting up the syslog output mode and it works fine, but it doesn't contain the server name, only the source ip and port, whereas text files contain the whole `[2021-07-05 09:54:21,619] [honeypotslogger_QSMBServer_311f76fe] [INFO]` header that lets us identify the service and destination port.

Would it be possible to include the servername in the syslog output?

**Comment by giga-a** [comment]
No worries, added in https://github.com/qeeqbox/honeypots/commit/5ae25fad72494e160b71d22528b7029165bf9c20
Let me know if it works or not..

**Comment by desoul99** [comment]
I tested it a bit today and it seems like it's working fine.
Thanks for the quick answer and resolution!

**Comment by giga-a** [comment]
Great!

**Comment by giga-a** [comment]
@santiagz I reproduced it

The fix is super easy, you need to add the `"syslog_address": "udp://localhost:514"`

Try this
```json
{
    "logs":"syslog",
    "logs_location":"",
    "syslog_address": "udp://localhost:514",
    "syslog_facility": 3,
    "honeypots": {
        "ftp": {
            "port": 21,
            "ip": "0.0.0.0",
            "username": "test",
            "password": "test"
            }
        }
}

```
