### ISSUE TITLE
getattrib: NT_STATUS_INVALID_NETWORK_RESPONSE

### ISSUE THREAD

**Issue by abdbacha** [qeeqbox/honeypots#5]
Hey @giga-a about #3
I tried it and it works fine, I was able to add multiple folders, subfolders and files
But when I try to get a file this error appears
`getattrib: NT_STATUS_INVALID_NETWORK_RESPONSE`
And the received folder will be empty.

**Comment by giga-a** [comment]
Hey! can you share the command that you used to retrieve the folders & files?

**Comment by abdbacha** [comment]
Hey,
Sure, the commend i used is:
'get _folder name_ '

**Comment by giga-a** [comment]
@abdbacha, 

Were you using `smbclient`?

I think that issue related to `smbclient` configuration and not the honeypots package (I will dig deep into this later on)

For now, try using `smbclient.py` instead `smbclient` as `username:password@ip`

```bash
pip3 install impacket
smbclient.py test:test@127.0.0.1
shares
user share_name
get file_name
...
```
