### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by DEANCHIQ** [qeeqbox/honeypots#66]
I'm trying to install according to the instructions with pre-installation of packages, I'm faced with the need to "--break-system-packages" and replace "python-psycopg2" with "python3-psycopg2". Everything seems to be going well, but no commands are working. If trying through some .py I receive "No module named 'honeypots'". OS Ubuntu 24.04 server.

**Comment by DEANCHIQ** [comment]
Fixed by installing Python 3.8.0 (pre-installed 3.12.3 on Ubuntu 24.04).

**Comment by sysfu** [comment]
> Python 3.8.0

Can you recommend a howto guide for installing Python 3.8 on 24.04 LTS?
