### ISSUE TITLE
ImportError: cannot import name 'alarm' from 'signal' (C:\Python37\lib\signal.py )

### ISSUE THREAD

**Issue by shimxx** [qeeqbox/honeypots#7]
HI,When I finish the install，i try run it，input `python38 -m honeypots --setup ssh`
but I get back this error message:
`Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python37\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Python37\lib\site-packages\honeypots\__init__.py", line 2, in <module
>
    from .__main__ import main_logic
  File "C:\Python37\lib\site-packages\honeypots\__main__.py", line 11, in <modul
e>
    from signal import signal, alarm, SIGALRM, SIG_IGN
ImportError: cannot import name 'alarm' from 'signal' (C:\Python37\lib\signal.py
)`

**Comment by giga-a** [comment]
Hey @shimxx, I'm guessing you are running this honeypots package on Windows? If yes, it won't work because it meant to be used on Linux

**Comment by shimxx** [comment]
yes, my server is Windows 2008. what will you plan to support Windows in the future?

**Comment by giga-a** [comment]
I'm pretty sure that some of them work on windows but not all of them - let me check!

**Comment by shimxx** [comment]
Thanks for the quick answer, Let me colse issues. first
