### ISSUE TITLE
Some simple errors. 

### ISSUE THREAD

**Issue by washuu** [qeeqbox/honeypots#9]
Hello, 

I'm running the build from scratch on fresh Debian Bullseye. And I spotted some small issues: 

The chains DOCKER-ISOLATION-STAGE-1 and DOCKER in NAT table were non-existing, and I needed to create them manually: 
`1) Setup requirements (docker, docker-compose)
2) Test the project (All servers and Sniffer)
7) Run deploy
8) Run dev
9) Run test
> 2
Creating network "chameleon_backend" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable DROP INCOMING rule:  (iptables failed: iptables --wait -I DOCKER-ISOL
ATION-STAGE-1 -i br-a6a9464b3680 ! -d 172.24.0.0/16 -j DROP: iptables: No chain/target/match by that name.
 (exit status 1))` 

The SMTP honeypot attempted to bind to 0.0.0.0 and it conflicted with my exim listening on 127.0.0.1, despite the fact I specified the interface and IP in the config.json file: 

`Creating chameleon_honeypots_1 ...
Creating chameleon_honeypots_1 ... error

ERROR: for chameleon_honeypots_1  Cannot start service honeypots: driver failed programming external connectivity on end
point chameleon_honeypots_1 (7e0036301eb639a89e86d6b23ae5fb5ddab19936a3a019ffac92c29ee90195ac): Error starting userland
proxy: listen tcp4 0.0.0.0:25: bind: address already in use`

Even after disabling my exim temporarily, I got errors in testing: 
honeypots_1  | honeypotslogger_QSMTPServer_e260509b - postgres connection is good
honeypots_1  | Traceback (most recent call last):
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/honeypots/smtp_server.py", line 156, in <module>
honeypots_1  |     qsmtpserver.run_server()
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/honeypots/smtp_server.py", line 126, in run_server
honeypots_1  |     self.smtp_server_main()
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/honeypots/smtp_server.py", line 103, in smtp_server_main
honeypots_1  |     CustomSMTPServer((self.ip, self.port), None)
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/honeypots/smtp_server.py", line 94, in __init__
honeypots_1  |     SMTPServer.__init__(self, localaddr, remoteaddr)
honeypots_1  |   File "/usr/local/lib/python3.8/smtpd.py", line 650, in __init__
honeypots_1  |     self.bind(localaddr)
honeypots_1  |   File "/usr/local/lib/python3.8/asyncore.py", line 326, in bind
honeypots_1  |     return self.socket.bind(addr)
honeypots_1  | OSError: [Errno 99] Cannot assign requested address
`

Some errors about SMB2: 

 Traceback (most recent call last):
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/impacket/smbserver.py", line 4270, in processRequest
honeypots_1  |     respCommands, respPackets, errorCode = self.__smb2Commands[smb2.SMB2_NEGOTIATE](
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/impacket/smbserver.py", line 2696, in smb2Negotiate
honeypots_1  |     raise Exception('SMB2 not supported, fallbacking')
honeypots_1  | Exception: SMB2 not supported, fallbacking
honeypots_1  | Traceback (most recent call last):
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/impacket/smbserver.py", line 4270, in processRequest
honeypots_1  |     respCommands, respPackets, errorCode = self.__smb2Commands[smb2.SMB2_NEGOTIATE](
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/impacket/smbserver.py", line 2696, in smb2Negotiate
honeypots_1  |     raise Exception('SMB2 not supported, fallbacking')
honeypots_1  | Exception: SMB2 not supported, fallbacking
`
And SSH: 

honeypots_1  | honeypotslogger_QSSHServer_321de821 - postgres connection is good
honeypots_1  | Exception: Error reading SSH protocol banner
honeypots_1  | Traceback (most recent call last):
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
honeypots_1  |     buf = self.packetizer.readline(timeout)
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
honeypots_1  |     buf += self._read_timeout(timeout)
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
honeypots_1  |     raise EOFError()
honeypots_1  | EOFError
honeypots_1  |
honeypots_1  | During handling of the above exception, another exception occurred:
honeypots_1  |
honeypots_1  | Traceback (most recent call last):
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
honeypots_1  |     self._check_banner()
honeypots_1  |   File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
honeypots_1  |     raise SSHException(
honeypots_1  | paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
honeypots_1  |`

Please let me know if you want to get some additional information about my system, in order to help fixing these small issues.

**Comment by giga-a** [comment]
Hey @washuu, thanks for opening this issue,
I think I have an idea of what's going on..

Would you mind telling me the output of running this command `./run.sh test`

**Comment by washuu** [comment]
[chameleon.log](https://github.com/qeeqbox/honeypots/files/6988916/chameleon.log)
Hello, 

please see the log file. Nothing very unusual, please note port 25 missing in nmap scan.

**Comment by washuu** [comment]
BTW: When I removed the interface definition from the config.json, the network binding error  disappears and the honeypot starts correctly (nmap also detects it). But the honeypots are bound to all interfaces: 
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      652643/docker-proxy

As for the errors about SSH and SMB2 mentioned in the original post, they still stand true when using "deploy" option.

**Comment by giga-a** [comment]
> please see the log file. Nothing very unusual, please note port 25 missing in nmap scan.

Thanks for sending your log file! True, nothing unusual expect binding to that used address :+1: 

> BTW: When I removed the interface definition from the config.json, the network binding error disappears and the honeypot starts correctly (nmap also detects it). But the honeypots are bound to all interfaces:
> tcp 0 0 0.0.0.0:25 0.0.0.0:* LISTEN 652643/docker-proxy

That `config.json` is where you add/change/remove configurations, this file also used in the deploy option. Take a look at this https://github.com/qeeqbox/chameleon/issues/4#issuecomment-862911685

Try changing the smtp port to something else (for now)
```json
        "smtp": {
            "port": 2525,
            "username": "test",
            "password": "test"
        },
```
